services:
  fastapi_app:
    container_name: WEB_APP
    build:
      context: "."
      dockerfile: Dockerfile
    command: uvicorn app.backend.main:app --workers 1 --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - migration

  redis:
    image: redis:7
    container_name: REDIS
    ports:
      - "6379:6379"
    restart: unless-stopped

  worker:
    container_name: CELERY_WORKER
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DB_HOST: db
    depends_on:
      - redis
      - db

  db:
    image: postgres:15
    container_name: DEV_POSTGRES
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/db-files
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./logs/postgres:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3

  migration:
    container_name: MIGRATION
    command: sh -c "alembic upgrade head"
    build:
      context: "."
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: PUBLIC_TUNNEL
    command: tunnel --url http://fastapi_app:5000 --no-autoupdate
    restart: unless-stopped
    depends_on:
      - fastapi_app


volumes:
  postgres_data: