services:
  telegram_bot:
    container_name: BOT
    command: python3 -m app.bot.main
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    env_file:
      - .env


  fastapi_app:
    ports:
      - "5000:5000"
    container_name: WEB_APP
    command: >
      # /scripts/wait-for-it.sh ${DB_HOST}:${DB_PORT} -t 15 -- 
      # uvicorn app.backend.main:app --workers 1 --host 0.0.0.0 --port 5000
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/scripts
      - ./logs/postgres:/mining/logs/postgres
    env_file:
      - .env
    

  db:
    image: postgres:15
    container_name: DEV_POSTGRES
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/db-files
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./logs/postgres:/var/log/postgresql


volumes:
  postgres_data: