services:
  fastapi_app:
    container_name: WEB_APP
    build:
      context: "."
      dockerfile: Dockerfile
    command: uvicorn app.backend.main:app --workers 1 --host 0.0.0.0 --port 5000
    ports:
       - "6666:5000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db
      - migration
    volumes:
    - /www/api.dev.u-bro.ru/staticfiles:/app/staticfiles

  db:
    image: postgres:15
    container_name: DEV_POSTGRES
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/db-files
      PGPORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./logs/postgres:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3

  migration:
    container_name: MIGRATION
    command: sh -c "alembic upgrade head"
    build:
      context: "."
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

  admin_service:
    container_name: ADMIN_PANEL
    build:
      context: "./admin_service"
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_SCHEMA: admin_public
    depends_on:
      - migration
      - db


volumes:
  postgres_data: