services:
  fastapi_app:
    container_name: WEB_APP
    build:
      context: "."
      dockerfile: Dockerfile
    command: uvicorn app.backend.main:app --workers 1 --host 0.0.0.0 --port 5000
    ports:
       - "6666:5000"
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "db:host-gateway"
    volumes:
    - /www/api.dev.u-bro.ru/staticfiles:/app/staticfiles

  admin_service:
    container_name: ADMIN_PANEL
    build:
      context: "./admin_service"
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_SCHEMA: admin_public
    extra_hosts:
      - "db:host-gateway"